name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Start services
      run: docker compose up -d

    - name: Wait for services to be ready
      run: |
        echo "Waiting for database to be ready..."
        timeout 120 bash -c 'until docker compose exec -T db pg_isready -U postgres; do echo "Waiting for postgres..."; sleep 2; done'

    - name: Install dependencies
      run: docker compose exec -T web bundle install

    - name: Setup database
      run: |
        echo "Setting up database..."
        docker compose exec -T web rails db:create
        docker compose exec -T web rails db:migrate

    - name: Run RSpec tests
      run: docker compose exec -T web bundle exec rspec

    - name: Run Rubocop lint check
      run: docker compose exec -T web bundle exec rubocop

    - name: Run Brakeman security check
      run: docker compose exec -T web bundle exec brakeman --quiet --format json

    - name: Stop services
      if: always()
      run: docker compose down
