name: CI

# どのイベントが発生したら処理を実行するかを指定
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # ジョブを実行するOSを指定
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_database

    # jobをさらに細かくstepに分けてその処理を実行する
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6
        bundler-cache: true

    - name: Install libvips for image processing
      run: |
        sudo apt-get update
        sudo apt-get install -y libvips42 libvips-dev libvips-tools

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install JavaScript dependencies
      run: npm install

    - name: Build assets
      run: |
        npm run build
        npm run build:css

    - name: Setup database
      run: |
        echo "Setting up test database..."
        bundle exec rails db:create
        bundle exec rails db:migrate

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Run Rubocop lint check
      run: bundle exec rubocop

    - name: Run Brakeman security check
      run: bundle exec brakeman --quiet --format json
